- .github/PULL_REQUEST_TEMPLATE.md
Adds a template for a pull request, same as https://github.com/onfido/castor-icons/pull/7.
This closes issue #2.
> docs: pull request template

- .github/dependabot.yml
By default Dependabot setting is to open [maximum of 5 pull requests](https://github.com/onfido/castor/network/updates/71640981), then it waits until those are merged or closed. However, we do have e.g. Storybook that itself consists of 7 or more dependencies that should be upgraded all at once.
Increase [limit of possible pull requests to be opened](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit) to 10.
After merging Dependabot should be able to open up to 10 PRs.
N/A
> chore: limit dependabot open pull requests to 10

- .github/workflows/preview.yml
Deploy Storybook previews using [Surge](https://surge.sh/).
Using [Surge PR Preview](https://github.com/marketplace/actions/surge-pr-preview) action deploying only for pull requests, removing preview when PR is closed (e.g. merged).
Essentially when PRs are open at later stages, however tested [here](https://github.com/onfido/castor/pull/25).
N/A
> ci: surge preview

- CHANGELOG.md
- package.json
- packages/core/package.json
- packages/react/package.json
https://www.npmjs.com/package/@onfido/castor/v/1.0.0-rc.1
https://www.npmjs.com/package/@onfido/castor-react/v/1.0.0-rc.1
Merging version bump back to the `main` branch.
> chore: release 1.x.x

- .github/workflows/deploy.yml
- README.md
Storybook from main branch will be deployed for general use to GitHub Pages.
Use [GitHub Pages Deploy Action](https://github.com/JamesIves/github-pages-deploy-action) to deploy.
Tested using [test branch](https://github.com/onfido/castor/actions/runs/394266529).
N/A
> ci: pages deploy

- .github/workflows/deploy.yml
Our primary branch is `main` not `master`, so it should also be used across CI scripts.
Incorrect name introduced with https://github.com/onfido/castor/pull/30.
Rename primary branch as `main`.
When merging to main branch deployment to GitHub Pages should start.
N/A
> ci: correct naming main branch

- .github/workflows/preview.yml
Surge preview [was added](https://github.com/onfido/castor/pull/26) with possibility to teardown it after PR is merged/closed (following [official example](https://github.com/marketplace/actions/surge-pr-preview#teardown)), however PRs then  [started to fail after merge](https://github.com/onfido/castor/pulls?q=is%3Apr+is%3Aclosed).
Not setting `with:ref` in script, following full example.
If this does not work, we can also [not teardown previews](https://github.com/onfido/castor/pull/32).
After merging PRs should not be failed.
N/A
> ci: correct surge teardown

- packages/react/src/icon/icon.react.tsx
Link to repositories should be to GitHub instead of (old) GitLab.
Fixing location of [Castor Icons](https://github.com/onfido/castor-icons).
N/A
> docs(react): correct castor-icons repository link

- packages/core/src/components/button/button.scss
- packages/core/src/components/input/input.scss
- packages/core/src/components/textarea/textarea.scss
Components to not have transition (animation) to feel more snappy.
Remove transition from all components.
N/A
> feat(core): remove component transition

- .github/workflows/preview.yml
Releasing a major version [merging version bump back to main](https://github.com/onfido/castor/pull/27) but preview for such is not needed.
Ignore "release" branches from generating previews.
Regular PRs should generate previews, but release branches should not.
N/A
> ci: ignore previews on release branches

- .github/workflows/preview.yml
Currently preview pipeline [succeeds even in case of error](https://github.com/onfido/castor/runs/1517210064?check_suite_focus=true#step:3:3188).
Set config to [fail pipeline on error](https://github.com/afc163/surge-preview#inputs).
Unfortunately this cannot be tested until merged to `main`... After which each PR with failing build of a preview will also be marked as failing.
N/A
> ci: fail preview on error

- .github/workflows/preview.yml
Currently previews generated on pull requests [checks out main branch](https://github.com/onfido/castor/runs/1512084267?check_suite_focus=true#step:2:365) instead of pull request one, causing a preview to not be the right one.
Setting reference of a merge to be the one used for building a preview Storybook instance.
This is based on [how action used does this itself](https://github.com/afc163/surge-preview/blob/main/.github/workflows/preview.yml#L13).
Unfortunately this cannot be tested until merged to `main`.
N/A
> ci: preview with merge ref

- docs/themer/themes.scss
Recent change [introduced new ways how theme is used](https://github.com/onfido/castor/pull/36), however the change was not applied to Storybook used themes.
This was not cought on pipeline because of [broken preview builder](https://github.com/onfido/castor/pull/58), and then resulted in `main` branch to now [be broken](https://github.com/onfido/castor/commit/d786ecdc21f3f9571862ea12bf4f2ffe1d665b2f).
Change theme usage on Storybook.
Build tested locally.
N/A
> docs: correct storybook themes

- .github/workflows/preview.yml
Surge preview [was added](https://github.com/onfido/castor/pull/26) with possibility to teardown it after PR is merged/closed (following [official example](https://github.com/marketplace/actions/surge-pr-preview#teardown)).
After this now [every PR fails when merging](https://github.com/onfido/castor/pulls?q=is%3Apr+is%3Aclosed), not clear why but I suspect teardown does not work.
Removing Surge preview teardown (at least for now).
After merging PRs should not be failed.
N/A
> ci: no surge teardown

- package.json
Additionally lint `*.scss` files when staged.
Add `lint-staged` configuration.
Tested locally.
N/A
> chore: lint staged scss files

- packages/core/src/helpers/color/color.scss
- packages/core/src/helpers/color/color.ts
- packages/core/src/theme/themes/day.scss
- packages/core/src/theme/themes/night.scss
Add new color alias "border-input-selected".
Adding new alias to both "day" and "night" themes.
N/A
N/A
> feat(core): add border-input-selected color alias

- .github/dependabot.yml
Upgrading [to webpack 5](https://github.com/onfido/castor/pull/89) on example [fails to build](https://github.com/onfido/castor/pull/89/checks?check_run_id=1537850143).
[After discussion](https://github.com/onfido/castor/pull/89#issuecomment-743228890) ignoring Dependabot to upgrade webpack to v5.
Ignoring is [based on official docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#ignore), that seem to not have possibility to ignore for specific workflow items.
Downside here that each future webpack major bump will need to be added to this ignore, or otherwise sorted.
This needs to be merged in order for Dependabot to take new config into consideration.
Our example will only demonstrate use case with webpack 4, …
> chore: dependabot ignore webpack 5 upgrades

- examples/custom-themes/src/themes/a.scss
- examples/custom-themes/src/themes/b.scss
- Have some testing for `castor.theme`
- Reuses class name defined by the mixin
- Cleans up implementation
Use `castor.theme` in `a` and `b` custom themes.
Local.
None.
> refactor(examples): use castor.theme mixin in custom-themes

- .eslintrc.json
- examples/.eslintrc.json
- examples/react-scss-js-webpack/webpack.config.js
Prevent incorrect usages of e.g. `document` and `require` by only allowing them in appropriate folders/files.
- Unset eslintrc env in the root config
- Create eslintrc in `examples` that extends the root and sets `env: browser`
- Use eslint comment in example `webpack` to set `env: node` just for that file
`npm run lint`
None.
> refactor(eslintrc): only set environment in the appropriate files

- packages/core/src/helpers/color/color.ts
- packages/core/src/helpers/font/font.ts
With newly introduced [template literal types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types) we can write terser code.
Reuse type variants as much as possible in `color` and `font`.
CI checks.
Highly subjective to personal preference.
Note: the outcome is still the same, hovering the type name shows the same type union.
> refactor: use template literal types for terser code

- .github/workflows/lint.yml
- .lintstagedrc.json
- package.json
Make sure both GitHub Actions and lint-staged target all appropriate files for each linter.
Keeping in mind that staged files already exclude files specified in `.gitignore`, in line with package.json scripts.
- Extract lint-staged config from package.json into its own config file (optional)
- Make `prettier` run for all staged files
- Make `eslint` run for all staged `js`, `jsx`, `ts` and `tsx` files
- Make `stylelint` run for all staged `css` and `scss` files
- Use `wearerequired/lint-action@v1` default extensions for `stylelint` and `prettier`, which cover all we need
Update files of all linted extensions, commit, confirm all linters run correctly.
lint-staged separate config file subject to personal taste.
> build: run linters for all appropriate files

- packages/core/src/utils/classy/classy.spec.ts
- packages/core/src/utils/classy/classy.ts
- packages/react/src/button/button.react.tsx
- packages/react/src/icon/icon.react.tsx
- packages/react/src/input/input.react.tsx
- packages/react/src/textarea/textarea.react.tsx
Reduce maintenance cost at little to no code ergonomic impact.
closes #47 
- Cut support for template strings which vastly simplifies `c` and `m`
- Reuse some logic between `classy` and `withPrefix`, namely `truthyNames`
- Jest unit tests
- Build process
`c` and `m` no longer support template strings
> refactor(core): simplify classy

- packages/core/src/helpers/color/color.ts
- packages/core/src/helpers/space/space.scss
- packages/core/src/helpers/space/space.spec.ts
- packages/core/src/helpers/space/space.ts
Refactors `space` for better maintainability, error messages, variable reutilisation, and parity between TS and Sass.
- Reuse `space`'s `allowedFloats` to interpolate floating numbers allowed
- Rename variables to match between languages
- Reorganise code structure to make them better match
`npm run test`
None?
> refactor(core): make "space" helper similar between .ts and .scss

- .npmrc
- yarn.lock
We currently use a mix of official npm and also Yarn registry to get dependencies.
Use only official npm registry.
Locally `yarn install`, on pipeline too.
N/A
> chore: use official npm registry

- .npmrc
- .yarnrc
Previously a change introduced a [usage of official npm registry](https://github.com/onfido/castor/pull/121), however as Yarn is used it also needs to be configured to keep using this registry.
Instead of setting registry for npm, now setting it for Yarn.
Locally tried to upgrade a package, and checked that registry persist.
Not sure how Dependabot will react to the change.
> chore: use official npm registry when executing yarn

- .dependabot/config.yml
- .github/dependabot.yml
- .yarnrc
- yarn.lock
As Dependabot integrated into GitHub (used currently) is in beta state, it _might_ be that the issue of timing out during the package upgrade scan is something internal. Also, it seems that even when [npm official registry is set](https://github.com/onfido/castor/pull/123) for Yarn to use (tested locally), it [does not work](https://github.com/onfido/castor/pull/122/files) with GitHub Dependabot ☹️
I prupose to (at least for now) to switch to legacy Dependabot Preview app.
First, new config has to be removed, then new config added (optional, but we need to exclude `webpack` from upgrading). Finally, repository will be a enabled on [Dependabot Preview config](https://app.dependabot.com/accounts/onfido/).
Can't really test it until merged to `main`.
Currently not able to enable app on …
> chore: use dependabot preview instead of github dependabot

- .github/dependabot.yml
Following https://github.com/onfido/castor/pull/124 removing usage of GitHub's Dependabot (beta) version completely, because still:
Removing `.dependabot.yml` removes integration.
Yet again, can't test this until merged...
Might be that Dependabot Preview app will still not work for some reason.
> chore: do not use github dependabot

- .dependabot/config.yml
Dependabot Preview by [default only adds "dependencies" label](https://dependabot.com/docs/config-file/#default_labels), and so is different from our previous usage as it was also setting "javascript" label:
Align with previous behaviours by also adding "javascript" label.
Can only be tested once Dependabot opens a new PR.
Don't know exactly how it works for other labels, e.g. "security" but should be all fine.
> chore: set default dependabot labels

- .github/workflows/lint.yml
Based on https://github.com/onfido/castor-icons/pull/15 we now use Dependabot Preview that has a different commit actor.
Change Dependabot actor from `dependabot` to `dependabot-preview`.
Only after merge - rebased Dependabot PRs should not be failing anymore.
N/A
> ci: commitlint exclude dependabot (preview)

- packages/react/src/components/index.ts
Export Search component for React.
Component can still be used, however can't be `import { Search } from "@onfido/castor-react"`.
Add to main component exports of React package.
Tested locally.
This might repeat for future components, @rabelloo we should think of testing the export of all components.
> fix(react): export search component

- packages/react/src/components/input/input.react.stories.tsx
- packages/react/src/components/input/input.react.tsx
- packages/react/src/components/search/search.react.stories.tsx
- packages/react/src/components/search/search.react.tsx
- packages/react/src/components/textarea/textarea.react.stories.tsx
- packages/react/src/components/textarea/textarea.react.tsx
Refactor (and align) form React components.
Make sure each form component has a ref forwarded (Textarea component did not have it), then make sure each has a `JSX.Element` as return type set.
In addition, we no longer be placing "max length" property on Storybook, as it's not part of custom (but default) properties of React form components.
Package build, Storybook.
N/A
> refactor(react): enhance form components

- packages/react/src/components/button/button.react.stories.tsx
- packages/react/src/components/icon/icon.react.stories.tsx
- packages/react/src/components/input/input.react.stories.tsx
- packages/react/src/components/search/search.react.stories.tsx
- packages/react/src/components/textarea/textarea.react.stories.tsx
Recently [component was not properly exported](https://github.com/onfido/castor/pull/141) and we had no easy way of testing such to potentially avoid in the future.
Within Storybook importing React components directly from `@onfido/castor-react` to make sure it replicates actualy package usage.
Storybook should function properly.
N/A
> refactor(react): import from castor-react package

- .stylelintrc.json
- packages/core/src/helpers/border-radius/border-radius.scss
- packages/core/src/helpers/color/color.scss
- packages/core/src/helpers/font/font.scss
- packages/core/src/helpers/space/space.scss
- packages/core/src/mixins/with-focus.scss
In case of same variable names used across different helpers/mixins, they would be unable to be imported into same index, instead those variables should be private.
In Sass private variables can be prefixed either with `_` or `-`.
Allowing `_` prefix for dollar variables and at functions, using such in core helpers and mixins.
On Storybook.
Breaks if someone would have been using those variables outside of Castor. However, because this is not official API we do not treat this as a breaking change.
> refactor(core): make sass variables private

- packages/react/src/components/textarea/textarea.react.stories.tsx
Add "resize" prop table options for Textarea component.
The change of story was probably due to component being wrapped in `withRef` utility.
Add Storybook configuration to add "resize" prop to table options.
On Storybook.
N/A
> docs: add textarea component "resize" table options

- packages/core/src/helpers/space/space.scss
- packages/core/src/helpers/space/space.spec.ts
- packages/core/src/helpers/space/space.ts
To simplify using `space` there should be any number allowed to be used.
Allowing any number to be used as multiplier for `space` helper.
Unit tests, on Storybook.
N/A
> feat(core): allow space to be used with any number

- .github/workflows/preview.yml
As described on https://github.com/onfido/castor/issues/159, we cannot use `pull_request_target` handler.
Temporary switch to only using `pull_request`, until switched to new preview provider.
Once PR merged.
N/A
> ci: preview on pull request

- packages/react/src/components/textarea/textarea.react.stories.tsx
After [adding "resize" table options to Textarea component](https://github.com/onfido/castor/pull/157) it is now not aligned with other type description that allow only certain "resize" prop to be set:
For example, on Button component we describe what "kind" prop can be set.
Modify table options to describe available "resize" prop values:
This also changes picker to "radio", same as used by default on Button component.
On Storybook.
Because this is not picked up from types by Storybook anymore (due to `withRef` wrapper usage), it needs to be manually aligned with any change made.
> docs: better describe textarea component "resize" variations

- packages/react/src/components/button/button.react.stories.tsx
Button component uses `<a>` tag when "href" prop is present.
A story starts with it being `undefined`, however when entering any value into "href" input on the story and then removing it, "href" prop becomes an empty string instead of previous `undefined` value, and this does not allow to revert component to use `<button>` tag so "disabled" prop is not working anymore.
Only set "href" prop to component when it has a value.
On Storybook.
N/A
> docs: don't set "href" key when value is empty string

- packages/core/src/components/radio/radio.scss
Design only requires to animate "dot" indicator of a Radio component.
Remove all other transitions, leave only for "dot" indicator transform.
On Storybook.
N/A
> fix: only animate radio "dot" appearance

- packages/core/src/components/radio/radio.scss
By design an invalid Radio does not have "checked" state styling of a bordered component applied.
Apply "checked" state styling for bordered but not invalid Radio component.
On Storybook.
Yet again increaset specificity.
> fix: do not apply "checked" state styling for invalid radio

- packages/react/src/components/input/input.react.tsx
- packages/react/src/components/search/search.react.tsx
- packages/react/src/components/textarea/textarea.react.tsx
- packages/react/src/utils/withRef.ts
Closes https://github.com/onfido/castor/issues/151
Explicitly name functions used inside `withRef` so that the function's name is used as `displayName`.
Go to Storybook, select their stories, click show code, confirm it shows the component name.
There's no way to guarantee `withRef` will be used with named functions in the future.
Anonymous functions will continue to have the same issue.
There is a lint rule for `forwardRed`, but then the types get all messed up (which `withRef` fixes).
> fix(react): withRef component displayNames

- packages/react/src/components/radio/radio.react.tsx
A [fix added display names](https://github.com/onfido/castor/pull/177) to React components that use `withRef` wrapper. However, Radio component did not have the fix applied.
Add `displayName` to Radio component.
On Storybook - component code examples should properly display the name of Radio component.
N/A
> fix(react): add display name to radio component

- packages/react/src/components/description/description.react.tsx
- packages/react/src/components/icon/icon.react.tsx
- packages/react/src/components/search/search.react.tsx
To make sure component notes are aligned and also visible on Storybook.
Removing usage of `@note` as then notes are not visible on Storybook, also making sure component names are quoted to align all component notes.
On Storybook mainly.
N/A
> docs: improve component notes

- packages/core/src/components/radio/radio.scss
- packages/react/src/components/radio/radio.react.stories.tsx
Fix CSS issue when children of Radio component are not correctly styled when input gets disabled.
Fix CSS selection when targetting children (including Decription component) of a disabled Radio component state.
In addition, this also improves complex CSS styling for Radio component comments.
On Storybook, Radio component story.
N/A
> fix(core): correctly style radio children when input is disabled

- packages/core/src/theme/tokens.json
WCAG guideline that states input borders need to have a 3:1 contrast ratio, so "neutral-600" (used
for input borders) must be adjusted accordingly.
Change "neutral-600" color token value.
On Storybook, inspecting input components.
N/A
> fix(core): correct "neutral-600" color due to accessibility

- packages/core/src/theme/themes/night.scss
WCAG guideline that states input borders need to have a 3:1 contrast ratio, input and action border colors must be adjusted on a night theme.
Adjust input/action border color on a night theme.
On Storybook.
N/A
> fix(core): correct input/action border color on night theme

- examples/react-emotion-ts-parcel/src/index.tsx
- package.json
- scripts/generate-tokens.ts
- yarn.lock
Automatically organise imports like VSCode does.
Temporarily use [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports) 
Upside is that it reuses TypeScripts runtime so it's exactly the same format.
Downsides listed on Risks.
Other options include:
- ESLint's rule `sort-imports` can only sort paths, not members
- [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) works well except for import members, uses alias instead of source name, and can't be configured at that level
- [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort) works well except for unnamed imports, always sorts them first regardless of path, and can be configured but has some logic that'd need to be changed. …
> build: automatically sort imports

- packages/core/src/components/input/input.scss
- packages/core/src/components/textarea/textarea.scss
- packages/core/src/mixins/as-text-input.scss
- packages/core/src/mixins/index.scss
Closes #207 
Refactors their styles to be shared in a mixin `as-text-input`.
That mixin also fixes the border specificity issue,
by applying it between `:hover` and `.-invalid`,
which requires a `stylelint` line disable.
Visually check the borders on focus.
None.
> fix(core): input and textarea borders on focus

- .stylelintrc.json
- packages/core/src/mixins/as-text-input.scss
- packages/core/src/mixins/index.scss
- packages/core/src/mixins/interactive.scss
- packages/core/src/mixins/with-inner-focus.scss
- packages/core/src/mixins/with-outer-focus.scss
- packages/core/src/mixins/wrap-if.scss
- packages/core/src/theme/theme.scss
Sass' `&` will output the selector twice,
which is why the linter disallows it,
and our conditional selectors should account for that.
Apply with `@if` instead of function `if` which allows for better content control.
Create mixin for shareability.
Check output CSS.
Reorders stylelint rule, `@include` before `$variable`, which honestly is a better separation and allows local variables to be used in mixins.
> fix: selectors applied conditionally

- .github/workflows/deploy.yml
Storybook is deployed to GitHub Pages via [GitHub Actions](https://github.com/JamesIves/github-pages-deploy-action), however a commit history is kept for the branch that is not needed.
Following https://github.com/onfido/castor-icons/pull/71.
Use `SINGLE_COMMIT` as [described in an action used](https://github.com/JamesIves/github-pages-deploy-action#optional-choices) to force-push to a target branch, this will not keep a deployment history.
Only once this gets merged to `main`.
N/A
> ci: deploy with single commit, don't keep history

- examples/react-scss-js-webpack/package.json
webpack can no longer start (probably after some version upgrade):
Use `webpack serve` [as suggested](https://github.com/webpack/webpack-dev-server/issues/2424#issuecomment-581319104).
Tested locally.
N/A
> build(examples): correctly start webpack

- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- yarn.lock
Dependabot does not currently upgrade majors of `@onfido/castor-icons`, however we actually can and need to have always the latest.
Allow to use _any_ version of `@onfido/castor-icons`.
This also upgrades to the latest.
After next major release of `@onfido/castor-icons` Dependabot should open a PR to upgrade.
Not entirely sure if Dependabot won't change the `*` indicating _any_ version.
> chore: use any @onfido/castor-icons version

- packages/core/src/helpers/border-radius/border-radius.scss
- packages/core/src/helpers/color/color.scss
- packages/core/src/helpers/font/font.scss
- packages/core/src/mixins/with-inner-focus.scss
- packages/core/src/mixins/with-outer-focus.scss
Always use built-in Sass modules.
Use `sass:list`  module instead of global function `index`.
Workflow build should pass.
Unfortunetly, this is not enabled [on `no-global-function-names`stylelint rule](https://github.com/kristerkari/stylelint-scss/blob/deb3e6bbe2d4a526412eff9b60b9ca00192e05ff/src/rules/no-global-function-names/README.md), maybe because it's not part of official [full list of disallowed names](https://github.com/sass/sass/blob/master/accepted/module-system.md#built-in-modules-1).
Nothing restricts from still using global `index`.
> refactor(core): use sass:list built-in module

- packages/core/style/components/button.scss
- packages/core/style/components/helper-text.scss
- packages/core/style/components/icon.scss
- packages/core/style/components/input.scss
- packages/core/style/components/radio.scss
- packages/core/style/components/search.scss
- packages/core/style/components/textarea.scss
For CSS build individual components will not be distributed, instead Sass is recommended to be used,
or dead code should be eliminated from "castor.css" file.
Remove generation of individual component CSS files for distribution.
On local build.
This is a breaking change - indicating with a note.
> feat(core)!: do not distribute individual component css files

- packages/core/src/internal/indicator-container/indicator-container.scss
As per design border radius of an `IndicatorComponent` should be 8px that is "large" token.
Switch from "medium" token to "large".
On Storybook visually.
N/A
> fix: correct indicator container border radius to "large"

- packages/core/src/components/checkbox/checkbox.scss
Styling for Checkbox "invalid" state is not right.
Fix styling to apply correct "invalid" colors for [checked] and [indeterminate] indicators, also outline.
On Storybook using "night" mode.
N/A
> fix(core): checkbox component "invalid" state styling

- packages/core/src/components/button/button.scss
- packages/core/src/internal/indicator-container/indicator-container.scss
- packages/react/src/components/button/button.react.stories.tsx
Using "gap" with Flexbox layout is not supported on iOS Safari, instead Grid layout is to be used.
Use "grid" instead of "flex" (incl. "inline").
On iOS Safari, and regular browser(s).
N/A
> fix: use "gap" with grid

- .eslintrc.json
- .versionrc.json
- scripts/bump-core-peer-dependency.cjs
When bumping a version, also bump "core" as peer dependency, in current case only "react" package.
Use a [custom updater for `standard-version`](https://github.com/conventional-changelog/standard-version#can-i-use-standard-version-for-additional-metadata-files-languages-or-version-files) to bump `@onfido/castor` as a peer dependency of `@onfido/castor-react`.
Unfortunetly, as the script is invoked by `standard-version` itself, I cannot use TypeScript here.
`yarn release --dry-run`
N/A
> build: bump "core" as peer dependency

- packages/react/src/internal/indicator-container/indicator-container.tsx
Define type for `<label>` element props once, then reuse.
Define individual type `LabelElementProps`.
N/A
N/A
> refactor(react): define <label> props type individually

- packages/react/README.md
Correct sentence "a lower ECMAScript version".
Correct spelling/sentence.
On GitHub itself.
N/A
> docs(react): correct spelling of "a lower ECMAScript version"

- packages/react/README.md
React `Fragment` is not properly styled when on GitHub docs.
Instead of shorthand using full `<Fragment />` component. Also, showing inclusion of React itself in examples.
Same as it was [done on Castor Icons](https://github.com/onfido/castor-icons/pull/64).
On GitHub itself.
N/A
> docs(react): improve example with a fragment

- docs/_react/intro.story.tsx
- packages/react/README.md
Make it clear to include `Icons` SVG sprite when using React `Icon` component.
Add instructions both on README ("react" package) and Storybook (React section).
On GitLab itself, then on Storybook preview.
N/A
> docs(react): inform to include "icons" sprite

- packages/react/README.md
Clearly inform that old browsers are not supported.
When mentioning IE11, also inform that Castor does not support old browsers.
On GitHub itlsef.
We do not actually have a list of supported browsers.
> docs(react): inform that old browsers are not supported

- docs/_core/intro.story.tsx
- docs/_react/intro.story.tsx
Storybook installation instructions are not clear enough on optional usage of  `@onfido/castor-icons`.
Instruct on how to additionally install `@onfido/castor-icons`.
Also, leave only instructions using npm, as Yarn is something that is individual per app and setup should be obvious based on their API.
On Storybook.
N/A
> docs: improve installation instructions of icons on storybook

- .dependabot/config.yml
Upgrading [to sass-loader 11](https://github.com/onfido/castor/pull/276) fails to build.
This is because it [no longer supports webpack 4](https://github.com/webpack-contrib/sass-loader/releases/tag/v11.0.0), that we need to use for our examples.
Adding this version to ignore list for Dependabot.
This needs to be merged in order for Dependabot to take new config into consideration.
Upgrade PR should close automatically too.
N/A
> chore: dependabot ignore sass-loader 11 upgrades

- packages/core/package.json
- packages/react/package.json
- scripts/bump-core-peer-dependency.cjs
Fix to allow newer versions too, like React 17 or castor-icons 2.
Change the versions.
npm should not complain about installing Castor with React 17 after merging.
None.
> fix: peer dependency versions

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/preview.yml
- .github/workflows/publish.yml
- CONTRIBUTING.md
Allow branches like `release/1.0.1` to be able to publish too.
Rename `release/*.x.x` to `release/*` in all CI related files.
Check CI after merge when a new `release/*` branch is created.
None, already changed GitHub branch settings.
> ci: rename release branches

- docs/spacer/react.tsx
- packages/core/src/components/field-label/field-label.scss
- packages/core/src/components/index.scss
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/field-label/field-label.tsx
- packages/react/src/components/index.ts
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/input/input.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
- packages/react/src/components/textarea/textarea.tsx
- packages/react/src/internal/field-label-wrapper/field-label-wrapper.tsx
- packages/react/src/internal/index.ts
Add FieldLabel component.
Implements FieldLabel component.
This closes issue #4.
N/A
> feat: add field-label component

- packages/core/src/components/field-label/field-label.scss
`FieldLabel` can be used either individually, or within (and next to) `Input` and `Textarea` components. But it always should follow an 8px grid.
Add padding for `FieldLabel` top/bottom of 2 x 4px, then use negative margin in case an input or textarea is used as children to remove the bottom padding.
On Storybook inspecting whole component composition so it follows 8px grid.
It assumes text is followed by input or textarea as last child.
> fix(core): make sure field-label follows 8px grid

- packages/core/src/components/index.scss
- packages/core/src/components/input/input.scss
- packages/core/src/components/textarea/textarea.scss
`FieldLabel` is not included within `Input` and `Textarea` automatically when children are passed (talking about React components here), so CSS should also include styling for such automatically.
Automatically include (only once) CSS for "field-label: component.
Locally, on Storybook.
CSS includes also in case label is not used.
> feat(core): automatically include field-label (for input/textarea)

- packages/react/src/components/field-label/field-label.stories.tsx
Misspelled "textarea".
Fixing spelling of "textarea" in React story of `FieldLabel`.
On Storybook.
N/A
> docs(react): correct field-label with textarea story

- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
`Input` and `Textarea` React components render labels using `children` prop, such bettern shown by default on stories.
Add labels by default on main stories of `Input` and `Textarea` components.
On Storybook.
N/A
> docs(react): show label by default on input and textarea

- packages/core/src/components/index.scss
Following https://github.com/onfido/castor/pull/293 main compilation of all components is wrong, as conditional inclusion uses `includes` for keeping a map of what has been included.
Rollback to checking for whether "field-label" was already included.
Another option is to exclude this component from a list of all components completely, however then we might introduce a bug when "field-label" is removed from both "input" and "textarea".
Tested local build.
N/A
> fix(core): compile field-label only once

- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/radio/radio.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
Form elements render labels when such are set via the `children` prop.
Inform about behaviour in Storybook stories of React.
On Storybook.
N/A
> docs(react): inform that form element children acts as labels

- packages/core/src/internal/indicator-container/indicator-container.scss
Placement of "bordered" indicator-container content is wrong.
Setting placement of content to be "start" position.
On Storybook checking `Checkbox` and `Radio` components with labels and "bordered".
N/A
> fix(core): correct placement of "bordered" indicator-container

- packages/react/src/components/field-label/field-label.stories.tsx
`FieldLabel` does not provide out-of-box solution for required and optional identification, such should be composed manually.
Two new stories shows how "optional" and "required" field labels can be composed.
On Storybook.
N/A
> docs: show how to make optional and required field-label

- packages/react/src/components/field-label/field-label.stories.tsx
Following [suggestion with a bug](https://github.com/onfido/castor/pull/292#discussion_r573784310) wrong color applied to indication of "required" field-label.
Change color to correct "negative" one.
On Storybook.
N/A
> docs: correct color of "required" field-label indication

- packages/react/src/components/field-label/field-label.stories.tsx
Improve "required" `FieldLabel` component example on Storybook, following the [existing implementation(https://github.com/onfido/castor/pull/292).
- use `<abbr>` tag
- set `aria-label` for a "required" field
On Storybook.
N/A
> docs: make better "required" field-label example

- packages/react/src/components/helper-text/helper-text.tsx
`HelperText` can be used within `Checkbox`, `Radio`, `FieldLabel` components.
Identify where `HelperText` can be used.
N/A
N/A
> docs(react): identify that helper-text also used for field-label

- packages/core/README.md
- packages/react/README.md
Having `@onfido/castor-icons` as peer dependency for types might be problematic when using TypeScript + npm v6 without icons.
Inform about situation, and provide recommendation on how to resolve the problem.
N/A
N/A
> docs: inform about using with typescript

- packages/core/src/components/asterisk/asterisk.scss
- packages/core/src/components/index.scss
- packages/react/src/components/asterisk/asterisk.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/index.ts
Add Asterisk component, that is used to identify a "required" FieldLabel.
Implements Validation component.
N/A
> feat: add asterisk component

- packages/core/src/internal/indicator-container/indicator-container.scss
Fixes Checkbox inside containers that force its width to be larger than its content.
Make the checkbox indicator use only its own width (`auto`) and the label use the rest of available space (`1fr`).
Can't reproduce on Storybook 🤔 
But essentially a `display: grid` parent and a Checkbox inside.
None.
> fix(core): correctly space full width checkbox and radio

- packages/core/src/components/checkbox/checkbox.scss
- packages/core/src/components/radio/radio.scss
- packages/core/src/internal/indicator-container/indicator-container.scss
Checkbox within "checked" and also "disabled" state has wrong styling:
- correctly styling "disabled" checkbox state via "after" and "before" pseudo selectors
- move background color change for "disabled" indicator container to "radio" (as this is only needed by it)
On Storybook.
N/A
> fix(core): correct "disabled" styling for checkbox and radio

- packages/core/src/components/checkbox/checkbox.scss
- packages/core/src/components/radio/radio.scss
- packages/core/src/internal/indicator-container/indicator-container.scss
- packages/core/src/mixins/as-text-input.scss
Enable upcoming `<Form>` and `<Field>` components, as well as customer specific implementations, to simply mark a field/input as `.-touched` to take full advantage of HTML5 validation.
Adding `.-touched` on blur is much simpler than replicating the entire validation logic in JavaScript.
This is even more valuable for non-React (or vanilla) customers that want minimal JS.
For example:
https://user-images.githubusercontent.com/18623773/108243003-7edc9700-7145-11eb-8cde-82f3d9976240.mov
Add `.-touched:invalid` to every occurrence of `.-invalid`.
Video above.
More power means more responsibility.
> feat(core): add .-touched:invalid as an alternative to .-invalid

- packages/core/src/components/fieldset-legend/fieldset-legend.scss
- packages/core/src/components/index.scss
- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.stories.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.tsx
- packages/react/src/components/index.ts
- packages/react/src/components/radio/radio.stories.tsx
Add FieldsetLegend component, that is used same as `<legend>` element within `<fieldset>`.
Implements FieldsetLegend component.
On Storybook preview, including Checkbox and Radio stories "with fieldset legend".
N/A
> feat: add fieldset-legend component

- .dependabot/config.yml
Upgrading [to autoprefixer 10](https://github.com/onfido/castor/pull/352) fails to build.
This is because it [is based on PostCSS 8](https://github.com/postcss/autoprefixer/releases/tag/10.0.0), and is [not supported by Parcel 1](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users#parcel) we currently use (with no intentions to upgrade for now).
Adding this version to ignore list for Dependabot.
This needs to be merged in order for Dependabot to take new config into consideration.
Upgrade PR should close automatically too.
N/A
> chore: dependabot ignore autoprefixer 10 upgrades

- .dependabot/config.yml
Upgrading [to postcss-modules 4](https://github.com/onfido/castor/pull/347) fails to build.
This is because it [is based on PostCSS 8](https://github.com/css-modules/postcss-modules/blob/master/CHANGELOG.md#400), and is [not supported by Parcel 1](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users#parcel) we currently use (with no intentions to upgrade for now).
Adding this version to ignore list for Dependabot.
This needs to be merged in order for Dependabot to take new config into consideration.
Upgrade PR should close automatically too.
N/A
> chore: dependabot ignore postcss-modules 4 upgrades

- docs/colors/colors.ts
- docs/colors/index.ts
- docs/colors/tokens.scss
- docs/index.ts
- docs/tokens.scss
- packages/react/src/components/icon/icon.stories.tsx
Picker for a Castor color (currently used on an `Icon` story only) does not include theme tokens.
This closes #152.
Merge themes, then import tokens and generate an array of color (tokens) available.
On Storybook, `Icon` story by changing a color.
If themes have different colors tokens set, then such would appear on a dropdown but can have no value.
This should not happen, but also something to think about on how a validation of theme tokens could be done to make sure each theme has all but not other tokens defined.
> docs: include theme color tokens for storybook

- packages/core/src/internal/indicator-container/indicator-container.scss
Fixes an issue where non-label Checkbox/Radio grids apply gap to a ghost column, because it is fixed in CSS.
Introduced in #327.
Invert the auto-flow grid axis back to column, but apply `auto` as a value for the rows.
Both in Storybook, fixes the described bug, and in Client Manager, desired behaviour described in #327 is kept.
None.
> fix: checkbox grid and ghost gap

- packages/core/src/internal/indicator-container/indicator-container.scss
Change current "transparent" background color of simulated input to "background-input".
Add background color of "background-input" to simulated input.
On Storybook.
N/A
> fix(core): correct background color of simulated input

- CONTRIBUTING.md
Correct `npm` command in example to be `Yarn` command (originally introduced via https://github.com/onfido/castor/pull/245).
Change example "release" command to use `Yarn`.
On GitHub itself.
N/A
> docs: correct "release" command example to use yarn instead of npm

- CONTRIBUTING.md
When releasing a non-latest minor/patch version, we no longer place back tags to keep track of changelog versioning. For this suggestion is to protect such branches against deletion.
Suggest to protect non-latest release branches.
On GitHub itself.
N/A
> docs: suggest to protect release branches

- packages/core/src/internal/indicator-container/indicator-container.scss
Bordered Checkbox and Radio is to have a background color of "background-input".
Set background color for IndicatorContainer when Checkbox and/or Radio is not disabled (for disabled it still stays as "transparent").
On Storybook.
N/A
> feat: set background color for "bordered" indicator container

- docs/themer/themes.scss
We allow to use "raw" version of a "classes" theme, that excludes base tokens. Base tokens can then be included separately, and only once.
For Storybook include base Castor tokens once, then use "day" and "night" themes in "raw" version.
On Storybook - theming should work, can inspect where what tokens are placed.
N/A
> docs: optimize storybook theming by including base tokens only once

- packages/react/src/components/search/search.tsx
Search component uses Input component under the hood, it also passes all the rest of the props to it.
Providing "children" to Input component renders a field label alongside an input.
This however breaks the Search component if allowed:
Exclude "children" from Search component props type.
Locally, when coding.
It does not disallow to still set children, e.g. if TS is not used.
However, designs point out that field labels should not even be used on Search component.
> fix(react): exclude "children" from search component props type

- .eslintrc.json
Such change would allow to e.g. discard some variables that are not used anywhere but should not travel further, like props that you pass to other components.
Use [linting rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) to setup a pattern to ignore, otherwise error.
Originally suggested by @rabelloo.
Tested locally in code.
N/A
> chore: allow to use underscored (starting with "_") unused vars

- packages/core/src/mixins/as-text-input.scss
Firefox has a reduced opacity set for placeholders.
Opacity should be aligned between each browser.
Set opacity so that each browser has aligned one.
On Storybook, using a few different browsers including Firefox.
N/A
> fix(core): set placeholder opacity so each browser is aligned

- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.story.tsx
- packages/core/src/components/textarea/textarea.ts
- packages/react/src/components/textarea/textarea.stories.tsx
After https://github.com/onfido/castor/pull/249 HTML (+ CSS) stories can now be added to each component.
Adding stories to Textarea component.
Please note this excludes stories that include FieldLabel and other components, as they're to come later with their stories.
On Storybook.
N/A
> docs: add html textarea stories

- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/input/input.story.tsx
- packages/core/src/components/input/input.ts
- packages/react/src/components/input/input.stories.tsx
After https://github.com/onfido/castor/pull/249 HTML (+ CSS) stories can now be added to each component.
Adding stories to Input component.
Please note this excludes stories that include FieldLabel and other components, as they're to come later with their stories.
On Storybook.
N/A
> docs: add html input stories

- packages/core/src/components/icon/icon.story.tsx
"color" helper is used but not imported.
Import "color" helper from Castor.
On Storybook, Icon component HTML story by changing icon fill color.
N/A
> docs: fix import of "color" helper

- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/button/button.ts
- packages/react/src/components/button/button.stories.tsx
Make some improvements to Button component stories.
Because of changed internal API for how stories are created, no longer needed to exclude "children" as it's now possible to change them in a story manually (instead of default "Button" value).
Also, type sorted alphabetically, and prop variation constants moved to the top to better align with new Input and Textarea component stories.
On Storybook, both "core" and "react" stories for Button component.
N/A
> docs: improve button stories

- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.story.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
[HTML story of Textarea component](https://github.com/onfido/castor/pull/420) had [incorrect "resize" prop use](https://github.com/onfido/castor/pull/420#discussion_r588268211), that instead should have been applied as a `style`.
Set "resize" via `style`, also fix default value on a story table.
Currently `style` is added simply as text value, however probably later might be good to have a helper function where objects could be passed.
On Storybook, Textarea component HTML story.
N/A
> docs: correct html textarea "resize", incl. story default value

- packages/core/src/components/input/input.stories.ts
Core and React stories should match, setting "value" is not needed however because of HTML story type it was added to the story table.
Omit "value" property for story.
On Storybook.
N/A
> docs: correct html input "value"

- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.story.tsx
"value" to `<textarea>` element cannot be set via `value` prop as for React, instead it should be `children`.
Use `children` to set value to `<textarea>` for HTML story.
If merged, https://github.com/onfido/castor/pull/424 is no longer needed.
On Storybook.
N/A
> docs: set html textarea story value as "children"

- packages/core/src/internal/indicator-container/indicator-container.scss
Label (text) has no correct pointer required on Checkbox and Radio components (incl. "disabled" state).
Remove pointer events for label text (children), allow pointer to be inherit from parent.
On Storybook.
If a link is to be added (although it's not recommended), it should then place the pointer events back for that link element.
> fix: correct pointer for checkbox/radio component label (text)

- .github/workflows/lint.yml
Switch to using our own custom commands to run varioius linters.
We don't use features provided by the linting action, and also this creates problems with PRs made out of forks.
Don't use action, run individual custom commands on a workflow.
Once merged to the `main` branch.
N/A
> ci: use custom lint commands

- packages/core/src/components/spinner/spinner.story.tsx
- packages/react/src/components/spinner/spinner.tsx
Default Spinner component to "medium" size.
Set default on React component, for HTML + CSS just default on a story.
On Storybook.
None - not yet released component.
> feat: default spinner as "medium" size

- packages/core/src/components/icon/icon.stories.ts
- packages/react/src/components/icon/icon.stories.tsx
"color" for Icon component has a list of available colors to apply, however Core story does not list colors properly.
Manually set table properties for both Core and React stories so that lists of colors available are aligned.
On Storybook, Icon component of each Core and React stories.
N/A
> docs: display "color" selection options in description

- packages/core/src/components/field/field.ts
- packages/react/src/components/field/field.tsx
- packages/react/src/components/field/useField.spec.ts
- packages/react/src/components/field/useField.ts
- packages/react/src/components/form/form.tsx
- packages/react/src/components/form/useForm.ts
Fixes an issue where form elements not wrapped by `<Field />` wouldn't represent the form disabled state.
Better merge `form` and `field` state in `useField`, which is the only hook form elements use.
Storybook.
None.
> fix: form disabled interactions

- packages/core/src/components/field-label/field-label.scss
Align FieldLabel width to be same as Input, which [recently changed to be 100%](https://github.com/onfido/castor/pull/439).
Set FieldLabel to also be 100%, so e.g. in case when it wraps an Input (or Textarea) component it could span to that wanted 100%.
On Storybook, inspecting React's Input and Textarea component stories that should be 100% and match Core stories.
N/A
> fix: align field label width with input/textarea

- packages/core/src/components/form/form.scss
- packages/react/src/components/form/form.stories.tsx
Fixes:
1. Form grid styles, so that children justify at start instead of stretching
2. Form story radios, so that they stack above each other
1. Apply `justify-items: start`
2. Display radio fieldset as column flex
Storybook. First issue was only observable in Firefox.
None.
> fix: form grid styles and story radios

- README.md
Add list of supported browsers (and versions).
This closes #243.
Add list of Chrome, Safari, Firefox, Edge browsers that we support with 2 last versions.
On https://github.com/onfido/castor/tree/docs/supported-browsers
N/A
> docs: add list of supported browsers

- README.md
- packages/core/README.md
- packages/react/README.md
After GitHub introducing built-in index (table of content), our current headings included additional symbols resulting in odd appearance in UI:
Move "dot" alongside badge to a newline after the heading on root and each package.
On https://github.com/onfido/castor/tree/docs/better-gh-index (root and also each package).
N/A
> docs: clean headings for better index

- packages/core/README.md
- packages/react/README.md
New badges to indicate bundle sizes.
Use [bundlephobia](https://github.com/pastelsky/bundlephobia) to analyze and display minzipped sizes.
On https://github.com/onfido/castor/tree/docs/bundle-size-badge
N/A
> docs: add badges to indicate bundle sizes

- .storybook/main.ts
Fixes Storybook constant building when running, which completely destroys the CPU.
Follow suggestion on https://github.com/storybookjs/storybook/issues/14342 to define folder as separate globs.
`yarn start`
None.
> build: fix storybook

- packages/react/README.md
React package instructions refer to core package installation, however to root repository instead of package itself.
Change link to core package location.
On GitHub itself: https://github.com/onfido/castor/tree/docs/link-from-react-to-core/packages/react
This always links to `main` tree.
> docs: correctly link from react to core instructions

- packages/react/src/components/button/button.tsx
Make sure `<Button href={undefined} />` renders a `<button>` and not an `<a>`.
`<Button href="" />` will now also render as `<button>`, as will any falsey value.
Check `href` for value and not just the key presence.
1. Go to https://onfido.github.io/castor/?path=/docs/react-button--all-combinations, no button is disabled as they all incorrectly render as `<a>`
2. Go to the same story (directly from url, navigating doesn't work) in this PR preview, the first rows should render as `<button>`
None.
> fix(react): change button href check from key to value

- packages/react/src/components/field/useField.ts
Fixes the `useField` hook types, which are currently just a Record of any.
Fix types on the helper function as well as the object return in `useField` itself.
Call `useField()` somewhere and check the types before and after.
None.
> fix(react): useField types

- packages/core/src/helpers/font/font.scss
Currently the monospace font definition is wrapped in quotes, so the font-family does not apply.
This unwraps the string so that it works.
`string.unquote` in Sass.
`@include castor.font('400-monospace')` should apply correctly.
None.
> fix(core): monospace font

- packages/core/src/theme/theme.scss
- packages/core/src/theme/themes/day.scss
- packages/core/src/theme/themes/night.scss
Currently the browser appearance does not adapt to Castor's set theme.
Most visible on a scrollbar:
Make it so ([browsers that support it](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#browser_compatibility)) do:
Extend the theme mixin to respond to a `dark` type, adding `color-scheme` accordingly.
Look at the output `themes/night.css` and `day.css`.
Some browsers like Firefox don't support it, but it should simply be ignored.
> feat(core): themes set color-scheme

- packages/react/src/components/field/field.tsx
React uses "minLength" prop, not "minlength" attribute.
Correct example with "minLength" prop.
N/A
N/A
> docs(react): correct example of field validation, "minLength" prop

- packages/react/src/components/button/button.stories.tsx
- packages/react/src/components/spinner/spinner.stories.tsx
After some Storybook upgrade a default radio is no longer being selected.
Use args to set the default, which then always selects it on a story.
Button and Spinner components, React stories on Storybook.
N/A
> docs(react): always select default radio

- packages/react/src/components/button/button.stories.tsx
After https://github.com/onfido/castor/pull/576 no longer need to set "href" prop on React story _only_ when it's not empty, component will not render as `<a>` now if href is set empty.
Pass all props to Button component.
On Storybook, React story for Button component should render as `<button>` when "href" prop is empty.
N/A
> docs(react): always set href for button even when it's empty string

- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
React Input & Textarea component stories "with validation" also has a "label" prop that is not needed, instead "children" should be used.
Remove extra "label" prop added to stories.
On Storybook, inspecting "with validation" React stories of Input and also Textarea components.
N/A
> docs(react): no "label" prop for input/textarea with validation stories

- .vscode/extensions.json
- .vscode/settings.json
We use `stylelint` however for VS Code it requires additional configuration and a plugin.
Set the recommended plugin of `stylelint`, then add configuration to auto format and fix styling upon saving (only HTML, CSS, SCSS).
Locally with VS Code.
Only affects VS Code users, hopefully contributers will be using this editor and installing recommended plugins.
> chore: configure stylelint with vscode

- .vscode/settings.json
We do try to fit code into 80 characters long (which is done by linters), however having a visual line would also allow to keep such for other stuff like inline comments.
Add ruler of 80 characters to VS Code.
Locally on VS Code.
Only affects users that would use VS Code.
> chore: configure rulers for vscode

- packages/react/src/components/form/getFormValues.spec.ts
- packages/react/src/components/form/getFormValues.ts
The current approach will read `id` off elements if they have one, instead of reading their `names`.
That's because of how `<form>.elements` work.
Instead of using the `elements` key, just list them as an array and filter the ones that have the `name` property set.
It's actually much more efficient this way, and we can remove some code.
Updated unit tests.
None.
> fix(react): form onSubmit values

- packages/core/src/helpers/font/font.scss
- packages/core/src/helpers/font/font.ts
When "Roboto Mono" is not available, the default `monospace` font in Chrome/MacOS is [Courier](https://en.wikipedia.org/wiki/Courier_(typeface)), which is a serif font and looks nothing like Roboto.
So, this improves the monospace list in case "Roboto Mono" isn't available.
Add `Consolas` for Windows and `Menlo` for MacOS.
Use monospace font helpers but don't provide "Roboto Mono".
None.
> feat(core): improve font monospace list

- packages/react/src/components/form/form.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/input/input.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
- packages/react/src/components/textarea/textarea.tsx
- packages/react/src/internal/field-label-wrapper/field-label-wrapper.tsx
Using "children" prop to display a label on React's Input and Textarea is not very accurate, because "children" on Textarea has another meaning, also e.g. for Select component this also will not work - options will need to be provided via children instead.
Deprecate usage of "children" prop on Input and Textarea components, suggest component composition instead.
N/A
N/A
> feat(react): deprecate "children" for adding input/textarea label

- CONTRIBUTING.md
On Markdown list with new line indentations code snippets do not get converted properly in UI.
Wrap code snippets with backticks, same as on other places in the doc.
On GitHub UI.
N/A
> docs: wrap code in list with backticks

- CONTRIBUTING.md
Improve and make E2E contributing information more accurate.
Detail running locally, CI differences and how to update snapshots.
We might go for Docker at some point, but then we can update documentation again.
> docs: add more E2E contributing information

- .github/workflows/lint.yml
Use Yarn always, as it's main dependency manager for this repository.
When running lint commands, due to a [recent change](https://github.com/onfido/castor/pull/442), npm is being used instead of Yarn.
Use Yarn to execute lint commands on CI.
N/A
N/A
> ci: use yarn to execute lint commands

- .eslintrc.json
- packages/react/src/components/form/form.stories.tsx
- packages/react/src/components/form/getFormValues.spec.ts
- packages/react/src/components/form/getFormValues.ts
Fix `Form` to read values properly depending on element attributes.
Check for element attributes and resolve value according to each of them.
Completely revamped the unit test suite.
Manual testing can be done on the story.
None.
> fix(react): form values onChange and onSubmit

- jest.config.js
- packages/core/src/components/asterisk/asterisk.story.tsx
- packages/core/src/components/button/button.story.tsx
- packages/core/src/components/field-label/field-label.story.tsx
- packages/core/src/components/field/field.story.tsx
- packages/core/src/components/helper-text/helper-text.story.tsx
- packages/core/src/components/icon/icon.story.tsx
- packages/core/src/components/icon/icon.ts
- packages/core/src/components/input/input.story.tsx
- packages/core/src/components/spinner/spinner.story.tsx
- packages/core/src/components/textarea/textarea.story.tsx
- packages/core/src/helpers/font/font.ts
- packages/core/src/utils/toCSS/toCSS.spec.ts
- packages/core/src/utils/toCSS/toCSS.ts
- packages/react/src/components/button/button.tsx
- packages/react/src/components/field/useField.spec.ts
- packages/react/src/components/field/useField.ts
- packages/react/src/components/form/form.stories.tsx
- packages/react/src/components/search/search.tsx
Keep imports consistent.
If import is exported via the package, import directly from it. Otherwise use relative path.
Only imports via relative paths are:
- internal components
- doc stuff
- in case it's a sibling file (e.g. if component has its own utilities)
- React utilities (not exported)
Pipeline should be green, Storybook should function as expected.
N/A
> refactor: import from package rather than relative path

- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/icon/icon.story.tsx
- packages/react/src/components/button/button.stories.tsx
For accessibility reasons icons inside buttons (that do have a button text) should have `aria-hidden="true"` set.
In examples add `aria-hidden="true"`.
On Storybook Core/React stories of Button with Icon.
N/A
> docs: add aria-hidden="true" to icons inside buttons

- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/react/src/components/form/form.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
Input and Textarea should always be connected to FieldLabel, even when it is nested - due to accessibility (screen readers).
In Storybook stories connect Inputs and Textareas to FieldLabels.
On Storybook, both Core and React stories of Input/Textarea with FieldLabel (and HelperText).
N/A
> docs: always connect label with input/textarea

- packages/react/src/components/form/form.stories.tsx
For accessibility it is recommend to set "autocomplete" for form field components.
Set given/family name, also email autocomplete options.
On Storybook.
N/A
> docs: set autocomplete on form example

- .bundlewatchrc.json
- .github/workflows/build.yml
- package.json
- yarn.lock
Add bundle size checking for #118 
Add bundle size checking for castor/core and castor/react packages' build files using `bundlewatch`. This check is done as part of build Github Action workflow but can also be done locally by running `yarn check:bundle-size`.
- Checked locally by tweaking `maxSize` in the `bundlewatch` config in `package.json` to deliberately trigger a failure when file size is above limit.
- PR build should also fail if this config's `maxSize` is changed to a value below the current sizes.
N/A (might be worth defining what maximum file sizes to start with, current limit is set based on rounding up current sizes for each package's files)
> build: check bundle size

- packages/core/src/components/validation/validation.ts
- packages/react/src/components/validation/validation.tsx
All component prop types that are to be reused across different frameworks (like also with Angular, Vue) should be set on a core package.
Move Validation component prop type "withIcon" from React package to Core.
N/A
N/A
> fix: correct "withIcon" validation prop type to be on core

- packages/core/src/components/button/button.story.tsx
- packages/core/src/components/field-label/field-label.story.tsx
- packages/core/src/components/field/field.story.tsx
- packages/core/src/components/helper-text/helper-text.story.tsx
- packages/core/src/components/spinner/spinner.story.tsx
- packages/core/src/components/textarea/textarea.story.tsx
When building core story for a component and "children" prop is in use, it's type should also accept `null` and `undefined`.
Improve "children" prop type to also accept `null` and `undefined`, leaving `string` or `string[]` variation untouched.
N/A
N/A
> docs(core): allow children in story to be null or undefined

- packages/react/src/components/search/search.tsx
- packages/react/src/components/validation/validation.tsx
Following https://github.com/onfido/castor/pull/703 icons used in other components should also be hidden from screen readers.
Hide icons in Search and Validation (React) components using `aria-hidden="true"`.
N/A
N/A
> fix(react): hide icon within component using aria

- packages/core/src/components/button/button.story.tsx
- packages/react/src/components/button/button.tsx
For accessibility, an anchor even if visually is looking like a button should not have a role of a "button" set, making it a button for screen readers.
Remove auto-setting "button" as a role on Button component, when it's meant to be rendered as an anchor.
Also, adjusting core story (fix is for React only, for Core it's just a doc change).
On Storybook, inspecting an element in DOM.
N/A
> fix(react): do not set role as "button" on button as anchor

- .github/workflows/lint.yml
- docs/helpers/html.ts
- e2e/tsconfig.json
- package.json
- tsconfig.json
Catch TS (type) errors ahead of time, especially in our examples, docs, and test files.
Also make prettier ignore files it doesn't know, like `.hbs`.
Run `tsc --noEmit` on lint.
Should output some logs in our pipeline.
Run `tsc --noEmit` on `main` and some errors will be found, fixed in this branch.
None.
> build: lint ts

- .github/dependabot.yml
Ignore certain dependencies from versions up.
Instead of ignoring specific major release versions, release anything above the specified versions.
As specified [in Dependabot docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore).
Once merged, a https://github.com/onfido/castor/pull/734 should be closed.
N/A
> chore: dependabot ignore all later versions

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
When upgrading Node version, we need to change it in multiple places. However, as we do use `.nvmrc` config, better to use such on CI also.
On CI, read Node version required from `.nvmrc` file, then use that when setting up Node.
On pipeline:
N/A
> ci: setup node version based on .nvmrc file

- .bundlewatchrc.json
- .github/workflows/build.yml
- CONTRIBUTING.md
- package.json
Following https://github.com/onfido/castor/pull/699 fix bundle size diff.
Tracking all `dist` JS and CSS files (of all packages) and prototypes, also setting `main` branch as base and the one to track.
In addition, setting max file sizes (subject to be reviewed), renaming script as "inspect".
Report on PR.
Not 100% sure diff will work, will need to be merged first in order to take effect.
> build: fix bundlewatch diff report

- packages/react/src/components/select/select.stories.tsx
Following https://github.com/onfido/castor/pull/704, Select should always be connected to FieldLabel, even when it is nested - due to accessibility (screen readers).
In Storybook React story connect Select to FieldLabel.
On Storybook, React story of Select with FieldLabel (and HelperText).
N/A
> docs(react): always connect label with select

- packages/react/src/components/form/form.stories.tsx
Add example with using Select (native) component with a Form.
Use Select (native) component to define gender in a form.
On Storybook, React story of Form component.
N/A
> docs(react): include select (native) component in form example

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Speed up CI jobs by caching Yarn.
Follow Node's [Yarn approach](https://github.com/actions/cache/blob/main/examples.md#node---yarn) to caching, using action.
N/A
N/A
> ci: cache yarn

- .storybook/main.ts
There was [an issue with webpack and Storybook](https://github.com/storybookjs/storybook/issues/14342), that was causing a constant build when running in development mode.
It was "fixed" in https://github.com/onfido/castor/pull/554.
However, now with upcoming Storybook v6.3 [it will be fixed](https://github.com/storybookjs/storybook/issues/14342#issuecomment-852015506), and such is no longer needed.
Remove the "fix".
Only after Storybook v6.3 upgrade.
N/A
> docs: remove webpack constant build issue "fix" on storybook

- packages/core/package.json
- packages/core/src/helpers/font/font.ts
- yarn.lock
Because a Font type within a helper uses CSSProperties that come from React dependency, a core package also requires React even for those who do not use it (but use TS).
Instead of using CSSProperties that require to have React as a dependency even for a core package, depend directly on `csstype`.
Downside - introducing a dependency.
Everything should still work as previously.
N/A
> fix(core): use css properties from csstype, do not rely on react

- packages/core/src/helpers/font/font.spec.ts
- packages/core/src/helpers/font/font.ts
Makes `toString` in the object that `font` helper returns non-enumerable so that CSS-in-JS tools won't try to apply it when using object notation, e.g.
```tsx
styled.div(font('300-regular'));
```
Define the property in an non-enumerable way with `Object.defineProperty`.
Unit tests' objects must match, and therefore no longer have `toString`.
> fix(core): font helper CSS-in-JS compatibility

- packages/react/src/components/asterisk/asterisk.tsx
- packages/react/src/components/button/button.tsx
- packages/react/src/components/checkbox/checkbox.tsx
- packages/react/src/components/field-label/field-label.tsx
- packages/react/src/components/field/field.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.tsx
- packages/react/src/components/fieldset/fieldset.tsx
- packages/react/src/components/form/form.tsx
- packages/react/src/components/helper-text/helper-text.tsx
- packages/react/src/components/icon/icon.tsx
- packages/react/src/components/input/input.tsx
- packages/react/src/components/progress/progress.tsx
- packages/react/src/components/radio/radio.tsx
- packages/react/src/components/search/search.tsx
- packages/react/src/components/select/select.tsx
- packages/react/src/components/spinner/spinner.tsx
- packages/react/src/components/textarea/textarea.tsx
- packages/react/src/components/validation/validation.tsx
Upcoming component Tooltip will be able to target any element, so we now have an use case for all components to expose their refs.
Add `withRef` to all components.
- Rendering each component with `ref={ref}` should work with no console logs/errors.
- Each component story's "view code" should still show the component with the correct name.
None.
> feat(react): forwardRef all components

- docs/decorators/container.scss
- packages/core/src/components/checkbox/checkbox.scss
- packages/core/src/internal/indicator-container/indicator-container.scss
Migrate Sass syntax since `/` for division is deprecated.
https://sass-lang.com/documentation/breaking-changes/slash-div
`npx sass-migrator division **/*.scss`
> refactor: migrate sass division

- .storybook/main.ts
TypeScript could not be upgraded because of [issue with `react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript/issues/356) (used on Storybook).
A [suggested "fix"](https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-857887751) [was applied](https://github.com/onfido/castor/commit/fa4158136cdb067a1895157dac1de4bc83867640) until issue resolved in v2 of `react-docgen-typescript`.
Remove a "fix".
Can only be tested once react-docgen-typescript v2 [is upgraded](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/43).
N/A
> docs: remove "fix" for using react-docgen with typescript on storybook

- Dockerfile.cypress
- docker-compose.yml
Docker image needs to be rebuilt each time a code (or config) is changed.
This is because files are copied over when building the image.
Instead of copying everything during build, mount additional volumes that are then being synced.
`packages` still need to be copied over during build, because `yarn install` needs to do some actions within these directories.
Tested locally, when modifying a file and running snapshot generation.
N/A
> test: mount additional volumes during e2e testing

- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/field-label/field-label.stories.ts
- packages/core/src/components/icon/icon.stories.ts
- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/popover/popover.stories.ts
- packages/core/src/components/progress/progress.stories.ts
- packages/core/src/components/select/select.stories.ts
- packages/core/src/components/spinner/spinner.stories.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/react/src/components/button/button.stories.tsx
- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.stories.tsx
- packages/react/src/components/icon/icon.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/popover/popover.stories.tsx
- packages/react/src/components/progress/progress.stories.tsx
- packages/react/src/components/radio/radio.stories.tsx
- packages/react/src/components/search/search.stories.tsx
- packages/react/src/components/select/select.stories.tsx
- packages/react/src/components/spinner/spinner.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
Omit Popover's class in its core story.
The second commit is just a refactor that simplifies types for Stories and the `omit` helper used in them.
Add `omit('class')`.
Look for `Story` and `omit` instances to simplify their types.
`class` should no longer appear in Core/Popover story table.
Everything else should be the same.
None.
> docs: omit popover class

- packages/core/src/components/tooltip/tooltip.stories.ts
- packages/react/src/components/tooltip/tooltip.stories.tsx
Use radios instead of boolean and story reset for Tooltip [show].
Use story control `inline-radio` rather than `boolean`.
Check Tooltip stories.
None
> docs: better control for Tooltip [show]

- packages/core/package.json
CSS can't be sideEffect free as it does not have an export, therefor when importing css into JS you lose it during the build process. 
Excluding it from tree shaking.
N/A
There is no risk, apart from an effect on bundle size
> chore: optimising sideEffect for importing CSS

- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/field-label/field-label.stories.ts
- packages/core/src/components/icon/icon.stories.ts
- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/popover/popover.stories.ts
- packages/core/src/components/progress/progress.stories.ts
- packages/core/src/components/select/select.stories.ts
- packages/core/src/components/spinner/spinner.stories.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/tooltip/tooltip.stories.ts
Rename Core/ stories to CSS/
Hopefully that makes it clearer for people unfamiliar with Castor, since "Core" could imply different meanings.
Differs from package/folder name, but shouldn't matter much as it's just a visual thing in docs.
> docs: rename Core to CSS

- package.json
Make local development faster.
Use `--modern` flag for `start-storybook`.
`yarn start`
Won't be able to use IE (not really a risk is it)
> build: use storybook --modern for local dev

- packages/react/src/components/popover/popover.tsx
Make popovers (when used with `target` ref) adjust their placement when intersecting with the viewport.
That is to ensure they would not be hidden depending on content and target placement.
https://user-images.githubusercontent.com/18623773/131711109-a417e36b-8f85-42f6-bc5e-25fddf93259f.mov
Use IntersectionObservers to capture events where the popover clips with the viewport.
Then, use an algorithm to find an optimal placement where the popover would not clip.
Works for both use cases, with and without `target` ref.
Storybook preview deploy.
1. The algorithm can not return to the preferred placement after an intersection event.
It will hold the optimal position until it clips too.
2. React exclusive feature.
> feat(react): popover screen aware

- packages/react/src/components/select/select.tsx
Currently empty states only work with `value`, but not `defaultValue`.
This PR fixes that.
Check both `defaultValue` and `value` for setting `-empty`.
Storybook preview.
None.
> fix: select empty state

- packages/react/src/components/tooltip/tooltip.tsx
TypeScript <4.4.x doesn't have `string` as part of the eventListener argument union, so type-checking fails on earlier versions.
However we don't need `string` anyway, so we can simplify the type.
Remove `string` from the union type (only used internally).
Lint with `tsc@4.3.5`
None.
> fix(react): tooltip type simplification

- packages/core/src/components/popover/popover.scss
- packages/core/src/components/tooltip/tooltip.scss
NOTE: will get merged as two different fixes, no squash, but still one PR because the second commit depends on the first
- Allow Popover to have `pointer-events`. Most content inside Popovers are clickable, like a dropdown menu
- Keep Tooltip visible on its own `:hover` state, as well as its target's
- Use `visibility` instead of `pointer-events`
- Add `:hover` rule for Tooltip
Preview
None.
> Fix / popover and tooltip pointer-events

- packages/react/src/components/select/custom/custom-select.tsx
- packages/react/src/components/select/select.stories.tsx
- packages/react/src/components/select/select.tsx
React `<Select/>` is not emitting `onChange` events.
Fix it so it does.
Inside `<CustomSelect/>`, when the `select` function is called, emit a synthetic event for 'change' from the native `<select/>` as if the user selected the option directly in it, instead of React modifying its value which is what actually happens.
- `onChange={console.log}` listener temporarily added in story to confirm.
- internal Onfido app Signal Builder (where we found the bug) has an e2e test that depends on that event, after the change it passes
If anything it reduces risk
> fix(react): select onChange

- packages/react/src/components/select/custom/custom-option.tsx
Non-native `<Select />` does not respect `[hidden]` attribute in `<Option />`.
`<Option hidden />` should not render, same as in native selects.
Useful for placeholders that you do not want in your popover/dropdown.
```tsx
<Select>
<Option hidden>Select an option...</Option>
</Select>
```
Using `disabled` works, but fits a different use case, in which you want the placeholder to be visible in the dropdown but not selectable.
In `CustomOption` return `null` if `hidden` is truthy.
Found in Signal Builder, reproduced and fixed in Storybook
None
> fix(react): hidden options do not render

- packages/react/src/components/select/select.tsx
Select `.-empty` modifier (for placeholders) is incorrectly applied when `defaultValue` is used, rather than `value`.
The problem is that the useEffect hook that trigger on `value` changes also triggers on first render, just after `useState(empty)`.
In that hook, we should only `setEmpty` if `defaultValue` is not defined.
Found in Signal Builder, reproduced and fixed in Storybook
None.
> fix(react): select empty modifier

- docs/helpers/matrix/reactMatrix.tsx
Prevent `console.error`s that show up in stories because `key` is not set.
Set a key for each component rendered inside `reactMatrix`.
Open Storybook locally, go to a story that uses the matrix such as Select's, check console for errors
None
> docs: set reactMatrix keys to stop console.error

- packages/react/src/components/select/select.stories.tsx
We use `disabled` in core/CSS/native Select because using `hidden` creates a bad user experience, as the next first option seems to be select by default.
However, in our "arguably better UX" version of Select, we can use `hidden` instead for a better "placeholder" experience.
Change `disabled` for `hidden`.
Storybook.
People might use `hidden` for `<Select native />`, which is fine but not ideal
> docs: select options - hidden instead of disabled

- packages/react/src/components/select/custom/custom-select.tsx
React's `<Select />` does not update when its `value` changes, but it should.
Introduce `useEffect` hooks that set internal value when it changes.
Also change `initialize` a bit so that the correct option JSX can be found with its value as key.
Storybook with `value` property defined and changed with, for example, hooks and buttons
Slightly increases `Select`'s bundle size
> fix(react): select should respond to value changes

- packages/react/src/components/select/custom/custom-select.tsx
Ensure it's impossible to not have an option selected.
In case the value provided has no related option, default to the first.
Also ensures a re-render on every option selection change, even if its value is nullish, so that it renders output correctly.
Storybook, provide `value` prop in story which does not match any available Option.
None
> fix(react): defaults Select to first option

- docs/_core/_core.stories.tsx
- docs/_core/borders/borders.stories.tsx
- docs/_core/colors/colors.stories.tsx
- docs/_core/spacing/spacing.stories.tsx
- docs/_core/theming/theming.stories.tsx
- docs/_core/typography/typography.stories.tsx
- docs/_react/_react.stories.tsx
Follow Storybook deprecation's instructions.
Rename imports from `'@storybook/addon-docs/blocks'` to `'@storybook/addon-docs'`
None
> chore: rename imports because of deprecation

- packages/react/src/components/select/custom/custom-select.tsx
- packages/react/src/components/select/select.tsx
- packages/react/src/utils/index.ts
- packages/react/src/utils/useForwardedRef/useForwardedRef.spec.ts
- packages/react/src/utils/useForwardedRef/useForwardedRef.ts
Expose Select's ref.
Use `withRef` and introduce new helper `useForwardedRef` to normalise a ref (function vs object) internally
Storybook, provide a reference to a Select component
None
> fix(react): expose Select's ref

- packages/react/src/components/select/custom/custom-select.tsx
Improve the condition for Select's options to render, otherwise a nullish `selectedOption` would incorrectly render it.
Use `options.size` instead, which is always `0` before the initialisation, and in case there are no `children` will simply render an empty `<div>`
Storybook
None, if no `children` is provided an empty `<div>` will be rendered.
> fix(react): condition for Select's options render

- packages/react/src/components/select/select.tsx
React to internal value changes to ensure a consistent "empty" state.
Re-check empty state just after a DOM cycle on every re-render.
Storybook, "All combinations" story should not show any "empty" state Selects.
None
> fix(react): select empty state check

- packages/react/src/components/select/custom/custom-select.tsx
Make sure Select has consistent height even if no output is rendered, when there are no options in it.
Always print a no-break-space at the end, ensuring the line-height will be applied by the browser.
Storybook, provide no children for a Select component.
None, does not affect its value or visuals.
> fix(react): ensure output's height

- docs/_core/colors/colors.scss
- docs/_core/colors/colors.stories.tsx
- docs/_core/colors/examples.story.tsx
- docs/_core/colors/helpers.story.tsx
- docs/_core/colors/intro.story.tsx
- docs/colors/colors.ts
- docs/colors/day.scss
- docs/colors/night.scss
Add examples to color documentation.
Display all colours dynamically depending on theme selected.
Storybook > Castor > Color > Examples
- ~~Non-component stories are currently out of order, but that regression was introduced some time ago.~~
~~Will open another PR to fix that~~
Actually that only happens locally, less priority then
- Not the best visualisation, but sets a minimum that we can improve over time.
Documentation as a whole will continue to be worked on in the near future
> docs: color examples

- docs/_core/borders/helpers.story.tsx
- docs/_core/colors/helpers.story.tsx
- docs/_core/spacing/helpers.story.tsx
- docs/_core/theming/creating-theme.story.tsx
- docs/_core/theming/intro.story.tsx
- docs/_core/typography/helpers.story.tsx
Fix Sass/CSS syntax highlight in stories.
Use `css` rather than `scss` or `sass` since only the first is supported.
Storybook -> Castor stories
None
> docs: syntax highlight for sass

- .github/dependabot.yml
Ignore `webpack-dev-server` in `examples/react-scss-js-webpack` too
Update `.dependabot.yml`
After merge should not open any dependabot PRs for that dependency
> build: update dependabot npm rules

- packages/react/src/components/popover/popover-with-portal.tsx
Make sure Popover/Tooltip/Select position is never wrong, even after layout shift or window scroll.
When Portal'ed, always calculate position on every render.
https://user-images.githubusercontent.com/18623773/146452684-22472fcf-fa5e-4e42-99f3-c9fa2da9513e.mov
None, we were already executing the function anyway, now it just applies to state.
> fix(react): popover position

- packages/react/tsconfig.json
Avoid red lines in code editors when importing Sass files.
Include `modules.d.ts` in `src/tsconfig.json`
Code editor should show red line on any `.scss` import in `src` before, but not after.
None.
> chore: include modules in src/tsconfig

- .storybook/custom/prepareForInline.tsx
Fix `prepareForInline` so that it only parses CSS.
Some React stories would break if we transformed all strings to TextNodes, like Select's.
Only parse if story id begins with `css-`
Select stories was broken before, couldn't select an option.
Now they're fixed.
None.
> docs: fix prepareForInline, only parse CSS stories

- docs/decorators/container.scss
Safari now supports flexbox gap, so we no longer need the margin workaround
Remove margin workaround, use gap
Stories should display exactly the same.
Button "disabled" is a good example.
Older versions of Safari won't display it properly, but it has low market share and it simply won't have spacing between elements in the story.
> refactor: container can now use flex gap

- .storybook/manager.ts
Have "Castor" in the browser title as a "suffix" rather than the default "Storybook"
MutationObserver on `<title>` element
Every story should have "Castor" as the browser title suffix
None
> docs: replace "Storybook" in title with "Castor"

- .storybook/custom/fixNames.ts
- .storybook/preview.ts
Some component names are not being correctly inferred by Storybook tools.
It is unclear why, as it was working in previous versions.
Hard-code problematic components' names in Storybook only.
Ideally we can simply remove this after tools work once again.
Check code snippet for all components (e.g. Spinner, Radio, Checkbox) before and after change
Temporary code tends to live longer than intended
> docs: fix some component names

- packages/core/src/components/select/select.stories.ts
- packages/core/src/components/select/select.story.tsx
- packages/react/src/components/search/search.stories.tsx
- packages/react/src/components/search/search.tsx
- packages/react/src/components/select/select.stories.tsx
- packages/react/src/components/select/select.tsx
- packages/react/src/internal/index.ts
- packages/react/src/internal/maybe-icon/maybe-icon.tsx
Some apps have a strict size restriction and can't simply include all `<Icons />` provided as an SVG sheet.
That means using `Select` and `Search` can have serious size implications.
Currently, their only option is to construct their own SVG sheet, presumably by taking the one provided by `@onfido/castor-icons` and removing unused icons.
This PR aims to offer an alternative in a per-component API to replace default icons.
Offer an `icon` prop that allows overriding default icon.
```tsx
import { IconSearch } from '@onfido/castor-icons';
<Search icon={<IconSearch />} />
```
Because the prop accepts a `JSX.Element`, it is not limited to `@onfido/castor-icons`, any React component's output will work.
Modified Select and Search stories, including a new story to demonstrate how to use the new …
> feat: allow external icon usage

- packages/core/src/components/combobox/combobox.scss
Combobox requires some other component styling in order to work properly.
If each component styling is included in the app individually (with Sass), some not included automatically.
Include required styles by default.
On app that requires individual component styling inclusion (e.g. SDK).
N/A
> fix(core): automatically include required component styles for combobox

- packages/core/src/components/field-label/field-label.scss
When a form component is used alongside field label, it requires some style adjustment.
Same as other components, include Combobox into adjustment selection.
N/A
N/A
> fix(core): adjust combobox styling when used alongside field label

- packages/react/src/components/option-list/options-list-init.tsx
- packages/react/src/components/select/custom/custom-select.tsx
Fix a case when options not initialized correctly with `value` or `defaultValue` set.
Initiate with 1st option only in case of no current value set, otherwise look up for it.
Tested locally via Storybook.
N/A
> fix(react): correctly init options when value (or defaultValue) provided

- packages/react/src/components/combobox/combobox.tsx
- packages/react/src/components/select/custom/custom-select.tsx
Correctly validate selected option on select/combobox.
When initiating - set value based on `value` on `defaultValue`, propagate `onChange` in case option value is set so that field could be properly validated, otherwise only adjust the placeholder.
This also required hidden Combobox component (that controls the form value) to be changed from `<input>` to `<select>`.
Tested via a form, locally.
N/A
> fix(react): correctly validate selected option on select/combobox

- packages/react/src/components/combobox/combobox.tsx
When clicking on Combobox, dropdown should open but input should not lose focus.
Don't focus on 1st option when clicking on component which opens a dropdown.
On Storybook.
N/A
> fix(react): don't focus on 1st option when clicking on combobox

- packages/react/src/components/select/custom/custom-select.tsx
Fixing bug where `CustomSelect` does not react when `value` is being changed for a component via the prop.
Listen for `value` change, set selection to that value.
Tested locally in a hacky way.
N/A
> fix(react): make sure custom-select reacts to value change

- package.json
Vercel upgrade NodeJS to version 18 causing issue with the build.
```Error: error:0308010C:digital envelope routines::unsupported```
Enforce NodeJS <18
N/A
N/A
> chore: enforce NodeJS <18

- packages/react/src/internal/indicator-container/indicator-container.tsx
Castor React typing is not compatible with React 18 projects.
They removed `{}` from `ReactFragment` type in React 18 (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56026):
So now, anything that does not match a `ReactNode` will fail type checking. And `JSX.IntrinsicElements['input']` type has no overlap with `ReactNode` type: it misses the `props` property.
The solution would be to do a union of `JSX.IntrinsicElements['input']` with `ReactElement`, to get the missing `props` property.
Tested with a React 18 project.
N/A
> fix: update IndicatorContainer children type

- packages/core/src/components/accordion/accordion.scss
- packages/core/src/components/index.scss
- packages/react/src/components/accordion/accordion.stories.tsx
- packages/react/src/components/accordion/accordion.tsx
- packages/react/src/components/index.ts
- yarn.lock
adds a new component : accordion
482
Adds Accordion component to Castor. 
Accordion component needs an array of AccordionItems to be rendered.
N/A
N/A
> feat(react): accordion component

- packages/react/src/components/option-list/option.tsx
OptionList component does not pass a11y checks. The Option component is missing a role:
```html
<label data-qa="bank_building_society_statement" class="ods-option">
<input readonly="" type="radio" aria-hidden="true">
<span role="option" class="ods-option-content"></span>
</label>
```
`input` is a children of a `role="list"` so it needs to have a role or to be marked as aria-hidden.
Because `input` is visually hidden it should be aria-hidden.
> fix(a11y): set  to hidden input
