onfido/castor

- .github/workflows/rebase.yml
Adding ability to rebase automatically.
Based on [GitHub action to automatically rebase PRs](https://github.com/cirrus-actions/rebase).
Will need to test on future PR, unfortunately.
N/A
> ci: automatic rebase

- packages/core/src/theme/themes/day.scss
- packages/core/src/theme/themes/night.scss
Update some colors for accessibility - backgrounds that used to be white, changing to slightly off-white.
Adjusting "white" background aliases.
N/A
N/A
> feat(core): adjust "white" background aliases

- packages/core/src/helpers/font/font.ts
Compact font objects for code readability.
Replace some new lines with spaces.
Completely subjective, feel free to decline.
> style: font sizes and types spacing

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.0.0-rc.2

- packages/core/src/mixins/with-focus.scss
One Sass variable [not changed](https://github.com/onfido/castor/pull/155/files#diff-5905f48216cf6a9bbdafbb87225ea629c5bea99b4c7fbffdd9a7afab5089d20eR20) when introdusing private variables.
Fix usage of Sass variable.
N/A
N/A
> fix(core): correct sass variable usage

- packages/core/src/components/button/button.scss
- packages/core/src/components/description/description.scss
- packages/core/src/components/description/description.ts
- packages/core/src/components/icon/icon.scss
- packages/core/src/components/index.scss
- packages/core/src/components/index.ts
- packages/core/src/components/input/input.scss
- packages/core/src/components/radio/radio.scss
- packages/core/src/components/radio/radio.ts
- packages/core/src/components/textarea/textarea.scss
- packages/core/src/mixins/index.scss
- packages/core/src/mixins/interactive.scss
- packages/core/src/mixins/square.scss
- packages/core/src/mixins/with-inner-focus.scss
- packages/core/src/mixins/with-outer-focus.scss
- packages/core/style/components/description.scss
- packages/core/style/components/radio.scss
- packages/react/src/components/description/description.react.tsx
- packages/react/src/components/index.ts
- packages/react/src/components/radio/radio.react.stories.tsx
- packages/react/src/components/radio/radio.react.tsx
Add Radio component.
Implements Radio component.
This closes issue #8.
N/A
> feat: add radio component

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.0.0-rc.3

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.0.0-rc.4

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.0.0

- .github/workflows/build.yml
- .github/workflows/preview.yml
- .github/workflows/publish.yml
- CONTRIBUTING.md
Improve release process.
Add step-by-step with the flow of releasing versions and pushing tags back to `main`, or leaving for non-latest releases.
With the next release probably.
N/A
> build: improve release process

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.0.1

- packages/core/src/components/field/field.scss
- packages/core/src/components/index.scss
- packages/core/src/components/index.ts
- packages/core/src/components/validation/validation.scss
- packages/core/src/components/validation/validation.ts
- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/field/field.tsx
- packages/react/src/components/index.ts
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/radio/radio.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
- packages/react/src/components/validation/validation.tsx
Add Validation component.
Implements Validation component.
This closes issue #5.
N/A
> feat: add validation component

- packages/core/src/components/fieldset/fieldset.scss
- packages/core/src/components/index.scss
- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/fieldset/fieldset.tsx
- packages/react/src/components/index.ts
- packages/react/src/components/radio/radio.stories.tsx
Add Fieldset component, that is used same as `<fieldset>` element.
Implements Fieldset component.
Later a FieldsetLegend component to be added that would make more sense.
On Storybook preview - Checkbox and Radio stories "with validation".
N/A
> feat: add fieldset component

- packages/core/src/theme/theme.scss
[Suggestion](https://github.com/onfido/castor/pull/330/commits/7a5745f79d738e28980ee3507574e322b195c74f) on https://github.com/onfido/castor/pull/330 breaks Prettier check on CI.
Fix (odd) Prettier issue by auto-formatting code.
CI pipeline should be fine.
N/A
> style: fix odd prettier issue with newline

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.1.0

- docs/_core/theming/creating-theme.story.tsx
- docs/_core/theming/intro.story.tsx
- docs/_core/theming/theming.stories.tsx
Theming is a difficult topic, that is better to be covered as much as possible - in such case, a Storybook instance should have some documentation.
Add Storybook story about theming basics, including creating a new theme.
On Storybook.
N/A
> docs: document theming on storybook

- packages/core/README.md
Jest setup requires additional step, that is not the default configuration.
Inform how to setup when testing with (JS) Jest.
N/A
N/A
> docs: inform how to setup jest test suite

- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/input/input.story.tsx
- packages/core/src/components/spinner/spinner.stories.tsx
- packages/core/src/components/spinner/spinner.story.tsx
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.story.tsx
Core (HTML + CSS) components do not have default props.
Remove defaults from stories.
Core Storybook stories.
N/A
> docs: don't set defaults for core stories

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.2.0

- docs/helpers/html.ts
- jest.config.js
- packages/core/src/components/asterisk/asterisk.story.tsx
- packages/core/src/components/field-label/field-label.stories.tsx
- packages/core/src/components/field-label/field-label.story.tsx
- packages/core/src/components/field/field.story.tsx
- packages/core/src/components/helper-text/helper-text.story.ts
- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/input/input.story.tsx
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.story.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
After https://github.com/onfido/castor/pull/249 HTML (+ CSS) stories can now be added to each component.
Adding stories to FieldLabel component.
Please note this excludes stories that include Validation component.
On Storybook.
N/A
> docs: add html field-label stories

- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/radio/radio.stories.tsx
Refactor React stories for Checkbox and Radio components.
Use `reactMatrix`, add "All Combinations".
On Storybook, React stories.
N/A
> docs(react): refactor checkbox & radio stories

- packages/react/src/components/button/button.tsx
Change style how comment is written redarging "disabled" button set from form.
Place comment next to "disabled" attribute, removing extra empty comment.
N/A
N/A
> style(react): comment regarding "disabled" button from form

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.3.0

- packages/core/src/components/asterisk/asterisk.story.tsx
- packages/core/src/components/field-label/field-label.stories.ts
- packages/react/src/components/asterisk/asterisk.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.stories.tsx
- packages/react/src/components/form/form.stories.tsx
It is not required to have a label for an asterisk.
Do not force setting label for asterisk.
N/A
N/A
> feat: do not force setting label for asterisk

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.4.0

- docs/helpers/docs.ts
- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/icon/icon.stories.ts
- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/progress/progress.stories.ts
- packages/core/src/components/select/select.stories.ts
- packages/core/src/components/spinner/spinner.stories.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/react/src/components/button/button.stories.tsx
- packages/react/src/components/icon/icon.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/progress/progress.stories.tsx
- packages/react/src/components/spinner/spinner.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
Improve some Storybook stories.
Mainly to make sure defaults are selected, also set on a table (excluding "core" stories, as they should not have defaults).
Also making sure available values to be styled as in other stories - `"<someting>"`.
On Storybook.
N/A
> docs: improve stories

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 1.5.0

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.0.1

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-parcel/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-parcel/package.json
- examples/react-emotion-ts-parcel/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-parcel/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.0.2

- docs/helpers/matrix/htmlMatrix.ts
- docs/helpers/matrix/reactMatrix.tsx
- docs/helpers/story.d.ts
- packages/core/src/components/button/button.stories.ts
- packages/core/src/components/checkbox/checkbox.stories.ts
- packages/core/src/components/field-label/field-label.stories.ts
- packages/core/src/components/icon/icon.stories.ts
- packages/core/src/components/input/input.stories.ts
- packages/core/src/components/popover/popover.stories.ts
- packages/core/src/components/progress/progress.stories.ts
- packages/core/src/components/select/select.stories.ts
- packages/core/src/components/spinner/spinner.stories.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/tooltip/tooltip.stories.ts
- packages/react/src/components/button/button.stories.tsx
- packages/react/src/components/checkbox/checkbox.stories.tsx
- packages/react/src/components/field-label/field-label.stories.tsx
- packages/react/src/components/fieldset-legend/fieldset-legend.stories.tsx
- packages/react/src/components/form/form.stories.tsx
- packages/react/src/components/icon/icon.stories.tsx
- packages/react/src/components/input/input.stories.tsx
- packages/react/src/components/popover/popover.stories.tsx
- packages/react/src/components/progress/progress.stories.tsx
- packages/react/src/components/radio/radio.stories.tsx
- packages/react/src/components/search/search.stories.tsx
- packages/react/src/components/select/select.stories.tsx
- packages/react/src/components/spinner/spinner.stories.tsx
- packages/react/src/components/textarea/textarea.stories.tsx
- packages/react/src/components/tooltip/tooltip.stories.tsx
Migrate from CSF2 to [CSF3](https://storybook.js.org/blog/component-story-format-3-0/)
Follow [Storybook's guide](https://storybook.js.org/blog/component-story-format-3-0/)
Storybook should continue to display the same thing
New format is a bit more verbose for a small amount of use cases, but better for most and also enables [interaction testing](https://storybook.js.org/blog/interaction-testing-sneak-peek/)
> docs: migrate to CSF3

- .storybook/custom/prepareForInline.tsx
Optimise `prepareForInline` custom function that we use in Storybook.
Remove unnecessary work, clean up types, and simplify functions.
Every "show source" code snippet should display exactly the same
None
> refactor: storybook custom prepareForInline

- .eslintrc.json
- docs/_core/_core.stories.tsx
- docs/_core/borders/borders.stories.tsx
- docs/_core/colors/colors.stories.tsx
- docs/_core/spacing/spacing.stories.tsx
- docs/_core/theming/theming.stories.tsx
- docs/_core/typography/typography.stories.tsx
- docs/_react/_react.stories.tsx
- package.json
- yarn.lock
Introduce [`eslint-plugin-storybook`](https://github.com/storybookjs/eslint-plugin-storybook) to ensure good practices, especially with new `play` and `render` functions.
Install, add `recommended` to `eslint.json`, customise one rule, fix offences, ignore a few others (we will probably rework some of these more custom stories into MDX in the near future).
CI should still pass.
None.
> build: introduce eslint-storybook

- .github/dependabot.yml
Fix dependabot's config.
Determine schedule which is mandatory.
Should pass CI linting.
None.
> build: fix dependabot config

- docs/_core/intro.stories.mdx
> docs: update quickstart wording

- yarn.lock
Automatically fix some dependabot PR conflicts in the lock file
Run `yarn`
> chore: yarn

- packages/react/src/components/popover/popover.tsx
Do not get stuck on "optimal position", after a new interaction (hover, focus) try preferred position again.
Popover will now try the preferred placement after every hover or focus.
Will continue to fallback to a better placement if the preferred one clips/intersects with the window.
https://user-images.githubusercontent.com/18623773/146467514-1c8297b4-c529-486a-a1fb-30c80ac5b854.mov
Slightly more computationally expensive.
> fix(react): popover placement

- .browserslistrc
Better reflects Castor's officially supported browsers
> chore: update browserslist

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.0.3

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
merge release 2.1.0 back into main
> chore(release): 2.1.0

- CONTRIBUTING.md
- README.md
The text is meant for contributors, not every user, it was a mistake putting it into the readme.
> chore: move from readme to contributing

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.2.0

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.2.1

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.2.3

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.2.4

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.2.5

- CHANGELOG.md
- examples/custom-themes/package.json
- examples/html-css-js-bundler/package.json
- examples/html-css-js/package.json
- examples/html-css/package.json
- examples/html-scss-ts-bundler/package.json
- examples/react-emotion-ts-bundler/package.json
- examples/react-scss-js-webpack/package.json
- examples/react-scss-ts-bundler/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
> chore(release): 2.3.0
